### ISSUE TITLE
图片仍然引用的是lydsy服务器上的文件

### ISSUE THREAD

**Issue by 111116** [Ruanxingzhi/bzojch#1]
## 例：BZOJ1002
```
<div><img width="157" height="159" alt="" src="http://www.lydsy.com/JudgeOnline/upload/201604/1(3).png" /></div>
<div><img width="422" height="412" alt="" src="http://www.lydsy.com/JudgeOnline/upload/201604/2(3).png" /></div>
```
<h3>题目描述</h3><p><p>　　轮状病毒有很多变种，所有轮状病毒的变种都是从一个轮状基产生的。一个N轮状基由圆环上N个不同的基原子<br />
和圆心处一个核原子构成的，2个原子之间的边表示这2个原子之间的信息通道。如下图所示</p>
<div><img width="157" height="159" alt="" src="http://www.lydsy.com/JudgeOnline/upload/201604/1(3).png" /></div>
<p>　　N轮状病毒的产生规律是在一个N轮状基中删去若干条边，使得各原子之间有唯一的信息通道，例如共有16个不<br />
同的3轮状病毒，如下图所示</p>
<div><img width="422" height="412" alt="" src="http://www.lydsy.com/JudgeOnline/upload/201604/2(3).png" /></div>

**Comment by Ruanxingzhi** [comment]
是的，这确实是一个大问题。

在下一个版本中，图片将会存到本地。

**Comment by Ruanxingzhi** [comment]
@111116 这个事情已经完成了。
由于文件太大（接近100MB），不是很适合传到Github。所以传到coding.net上面去了，这样下载速度会快一些。

请移步：[`https://coding.net/u/ruanxingzhi/p/bzojch/git`](https://coding.net/u/ruanxingzhi/p/bzojch/git)

**Comment by Ruanxingzhi** [comment]
已经同步到github上的版本。
